# setup environment
dist: trusty
sudo: false
language: ruby
cache: bundler

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-puppet"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
    rvm: 2.2.10
    env: VERSION='~> 4.10.12'
  - os: linux
    rvm: 2.2.10
    env: VERSION='~> 5.5.8'
  - os: linux
    rvm: 2.3.7
    env: VERSION='~> 6.0.4'
  - os: linux
    rvm: 2.3.7
    env: "ATOM_CHANNEL=beta VERSION='~> 5.5.8'"

# execute tests
install: gem install --no-document -v "$VERSION" puppet
before_script: puppet --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
