# setup environment
dist: focal
language: ruby
cache: bundler

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-puppet'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'

os: linux

matrix:
  include:
  - rvm: 2.2
    env: VERSION='~> 4.10.13'
  - rvm: 2.4
    env: VERSION='~> 5.5.22'
  - rvm: 2.6
    env: VERSION='~> 6.24.0'
  - rvm: 2.7
    env: VERSION='~> 7.9.0'

# execute tests
install: gem install --no-document -v "$VERSION" puppet
before_script: puppet --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
