# setup environment
dist: trusty
sudo: false
language: ruby
cache: bundler

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-puppet"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
    rvm: 2.2.8
    env: VERSION="'~> 3.8'"
  - os: linux
    rvm: 2.2.8
    env: VERSION="'~> 4.10'"
  - os: linux
    rvm: 2.2.8
    env: VERSION="'~> 5.0'"
  - os: linux
    rvm: 2.2.8
    env: ATOM_CHANNEL=beta

# execute tests
install: gem install --no-document -v $VERSION puppet
before_script: puppet --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
