# setup environment
dist: bionic
language: ruby
cache: bundler

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
    - APM_TEST_PACKAGES="language-puppet"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

matrix:
  include:
  - os: linux
    rvm: 2.2
    env: VERSION='~> 4.10.13'
  - os: linux
    rvm: 2.4
    env: VERSION='~> 5.5.22'
  - os: linux
    rvm: 2.6
    env: VERSION='~> 6.21.1'
  - os: linux
    rvm: 2.7
    env: "ATOM_CHANNEL=beta VERSION='~> 7.5.0'"

# execute tests
install: gem install --no-document -v "$VERSION" puppet
before_script: puppet --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
